<?php

namespace App\Models;

use App\Observers\PageObserver;
use Illuminate\Database\Eloquent\Model;

class PageTranslation extends Model
{
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $cacheRemover = Page::removeNavbarCache();

        self::updated($cacheRemover);
        self::deleted($cacheRemover);
    }

    protected $fillable = [
        'lang',
        'page_id',
        'title',
        'slug',
        'body',
        'meta_desc',
    ];

    public $timestamps = false;

}
